# Use a lightweight Python base image
#https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-pytorch
FROM nvcr.io/nvidia/l4t-pytorch:r32.4.4-pth1.6-py3


RUN pip3 install --upgrade pip

RUN apt-get update \
  && apt-get install -y \
  wget \
  curl


# COPY app.py /app/
COPY app.py upload.py flash_attn.py requirements.txt ./
RUN pip3 install --no-cache-dir -U -r ./requirements.txt


COPY Florence-2-base ./Florence-2-base

# Command to run your Python scripts sequentially
CMD ["python3", "-u", "app.py"]

