# Use a lightweight Python base image
FROM waggle/plugin-base:1.1.1-base

RUN apt-get update \
  && apt-get install -y \
  wget \
  curl


# COPY app.py /app/
COPY app.py upload.py flash_attn.py requirements.txt /app/
RUN pip3 install --no-cache-dir -U -r /app/requirements.txt
# Create cache directories
WORKDIR /app

COPY Florence-2-base ./Florence-2-base
ENV TRANSFORMERS_CACHE="/hf_cache"



# Command to run your Python scripts sequentially
CMD ["python", "-u", "app.py"]

