FROM python:3.11

RUN pip install transformers torch Pillow Requests
RUN pip install timm einops
WORKDIR /app
COPY Florence-2-base /app/Florence-2-base
COPY app.py /app
COPY flash_attn.py .

COPY icon.png /app/testphotos/

CMD ["python", "-u", "app.py"]