# Use a lightweight Python base image
FROM waggle/plugin-base:1.1.1-base

RUN apt-get update \
  && apt-get install -y \
  wget \
  curl


# COPY app.py /app/
COPY app.py upload.py flash_attn.py requirements.txt ./
RUN pip3 install -r ./requirements.txt


COPY Florence-2-base ./Florence-2-base


ENTRYPOINT ["python3", "-u", "app.py", "-stream", "bottom_camera"]

