# Use a lightweight Python base image
FROM python:3.11

# Install required dependencies
RUN pip install gradio==4.37.1 pandas==2.2.2 Pillow==10.3.0 Requests==2.32.3 sage_data_client==0.8.0 transformers==4.41.2 timm einops

# Set working directory
WORKDIR /app

# Create cache directories
ENV TRANSFORMERS_CACHE="/hf_cache"
RUN mkdir -p /app/sagePhotos

RUN touch data.json
# Copy your Python scripts and other necessary files
COPY FHugGradio.py flash_attn.py ./

# Expose port
EXPOSE 7860

# Set environment variables
ENV GRADIO_SERVER_NAME="0.0.0.0"
# Command to run your Python scripts sequentially
CMD ["python", "-u", "FHugGradio.py"]

